#include "eph.h"

int ephRdplan ( ephMOONctx* cmoon, ephPLANctx* cemb, ephPLANctx* cplan,
                double ut1, double tdb, int np,
                double elong, double phi, double hm,
                double *rast, double *dast,
                double *rapp, double *dapp, double* eo, double *diam )
/*
**  - - - - - - - - - -
**   e p h R d p l a n
**  - - - - - - - - - -
**
**  Topocentric apparent RA,Dec of a planet (also Sun and Moon),
**  and its angular diameter.
**
**  Given:
**     cmoon      ephMOONctx*  context for Moon (Note 2)
**     cemb       ephPLANctx*  context for EMB (Note 2)
**     cplan      ephPLANctx*  context for planet (Notes 2-4)
**     ut1        double       UT1 (MJD, Note 5)
**     tdb        double       TDB (MJD, Note 5)
**     np         int          body: 1 = Mercury
**                                   2 = Venus
**                                   3 = Moon
**                                   4 = Mars
**                                   5 = Jupiter
**                                   6 = Saturn
**                                   7 = Uranus
**                                   8 = Neptune
**                                else = Sun
**     elong      double       observer east longitude (radians)
**     phi        double       observer geodetic latitude (radians)
**     hm         double       observer height above sea level (meters)
**
**  Returned:
**     rast,dast  double*      RA, Dec (ICRS astrometric, radians)
**     rapp,dapp  double*      RA, Dec (topocentric apparent, radians)
**     eo         double*      equation of the origins (radians, Note 7)
**     diam       double*      angular diameter (equatorial, radians)
**
**  Returned (function value):
**                int         status: +1 = warning: date outside 1-4000
**                                     0 = OK
**                                    -1 = uninitialized context
**
**  Defined in eph.h:
**     ephPLANctx    planetary ephemeris context
**     ephMOONctx    lunar ephemeris context
**
**  Notes:
**
**  1  The ephemerides are calculated using the ELP/MPP02+VSOP2010
**     theories.  For the 21st century the results agree with JPL DE405
**     to the following geocentric accuracies:
**
**                       RMS          worst
**
**        Sun           0.243         0.559
**        Mercury       0.265         0.858
**        Venus         0.374         3.352
**        Moon          4.998         9.651
**        Mars          2.428        16.957
**        Jupiter       1.355         2.789
**        Saturn        1.435         3.294
**        Uranus        1.426         3.543
**        Neptune       1.433         2.916
**
**                       mas           mas
**
**     Comparisons with JPL DE430 are as follows:
**
**        Sun           1.329         1.841
**        Mercury       2.810         6.883
**        Venus         1.648         4.553
**        Moon         11.048        16.561
**        Mars          3.882        19.072
**        Jupiter      82.013       177.075
**        Saturn       92.820       164.302
**        Uranus      337.295       555.496
**        Neptune    1065.73       1883.56
**
**  2  The context arguments point to tables of constants that are used
**     by the lunar and planetary ephemeris functions ephMoon and
**     ephPlanet.  Before the present function is called, these three
**     context tables must be populated, by calling the function
**     ephMoonc in the case of cmoon (the Moon) and ephPlanc in the
**     cases of cemb and cplan (the Earth-Moon barycenter and the chosen
**     planet respectively).
**
**  3  It is the caller's responsibility to populate the cplan context
**     for the same planet that is identified by the argument np.
**
**  4  For np = 3 (Moon) or np = else (Sun), cplan is not used and can
**     be left uninitialized.  For np = 1 or 2 or 4-9, all three
**     contexts must be populated.
**
**  5  The date of observation must be supplied in two forms, namely
**     UT1 and TDB, both in the form of Modified Julian Date
**     (JD-2400000.5).  Depending on the application, liberties can be
**     taken:  usually TT will do instead of TDB and UTC instead of UT1,
**     and in some very low-precision applications UTC might be adequate
**     for both.  The particular need for Earth-rotation time as opposed
**     to what used to be called "ephemeris time" is for the accurate
**     computation of lunar geocentric parallax.
**
**  6  The observer location coordinates (elongm, phi, hm) allow
**     correction for geocentric parallax.  This is a major effect for
**     the Moon, but its effect on planetary positions is small
**     (for some applications negligible, especially for the outer
**     planets).  Geocentric positions can be generated by specifying
**     hm below -1000.0, for example "-1e6".
**
**  7  The "current" RA/Decs returned are topocentric apparent.  For
**     topocentric intermediate add the equation of the origins, eo.
**
**  8  See also the function ephRdplanq, which is more complicated to
**     call but will be faster in cases where more than one target is
**     involved.
**
**  Called:  ephMoon, ephPlanet, ephRdplanq
**
**  Last revision:   2021 October 9
**
**  Author P.T.Wallace - see license notice at end.
*/
{
   int j;


/* Position + velocity vectors (ICRS, au, au/s) */
   double pvgm[2][3],   /* geocenter to Moon */
          pvsb[2][3];   /* Sun to Earth-Moon barycenter */


/* Geocenter to Moon. */
   j = ephMoon ( cmoon, tdb, pvgm );
   if ( j ) return j;

/* Sun to Earth-Moon barycenter. */
   j = ephPlanet ( 3, cemb, tdb, pvsb );
   if ( j ) return j;

/* Call the "quick" version. */
   return ephRdplanq ( pvgm, pvsb, cplan, ut1, tdb, np, elong, phi, hm,
                       rast, dast, rapp, dapp, eo, diam );
}

/*----------------------------------------------------------------------
**
**  Copyright (C) 2021 by P.T.Wallace
**
**  Permission to use, copy, modify, and/or distribute this software for
**  any purpose with or without fee is hereby granted.
**
**  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
**  WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
**  WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
**  AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR
**  CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
**  OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
**  NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
**  CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
**
**--------------------------------------------------------------------*/
