#include "eph.h"
#include <string.h>
#include <stdio.h>

int ephTopc ( int ibody, char* path, ephTOPctx* c )
/*
**  - - - - - - - - -
**   e p h T o p c
**  - - - - - - - - -
**
**  Read from a binary .tctx file the context needed for TOP2013
**  outer-planet ephemeris computation.
**
**  Given:
**     ibody   int          body index:
**                            5: Jupiter
**                            6: Saturn
**                            7: Uranus
**                            8: Neptune
**     path    char*        directory path for .tctx files
**
**  Returned:
**     c       ephTOPctx*   context structure
**
**  Returned (function value):
**             int          status:
**                              0   no error
**                             -1   illegal ibody
**                             -2   file path+name too big
**                           else   file-related errors
**
**  Notes:
**
**  1  The .tctx binary files are generated by the eph_top_bin tool
**     (top_bin.c) from the TOP2013.dat ASCII file.  Use the .tctx
**     extension to distinguish from the VSOP2013 .ctx files — the two
**     structs are incompatible and cannot be interchanged.
**
**  2  ephTOPctx is large (~2 MB per body); always heap-allocate.
**
**  Reference:
**     J.-L. Simon et al., A&A 557, A49 (2013).
**
**  Called:  ephBopr
*/
{
#define LF_TOP (17)
   char namef[LF_TOP] = "TOP2013_#.tctx";
   char fname[LF_TOP];

   FILE* fp;
   int j;

/* Validate ibody. */
   if ( ibody < 5 || ibody > 8 ) return -1;

/* Generate name of binary file. */
   strncpy ( fname, namef, LF_TOP );
   *strchr ( fname, '#' ) = (char) ( '0' + ibody );

/* Open the binary file. */
   fp = ephBopr ( path, fname, &j );
   if ( j ) {
      printf ( "Failed to open file %s, error %d\n", fname, j );
      return j - 1;
   }

/* Read the context. */
   j = fread ( c, sizeof(ephTOPctx), 1, fp );
   if ( j != 1 ) {
      printf ( "Error reading file\n" );
      fclose ( fp );
      return -4;
   }

/* Close the file. */
   j = fclose ( fp );
   if ( j ) {
      printf ( "Error closing file %s\n", fname );
      return -5;
   }

/* Success. */
   return 0;
}

/*----------------------------------------------------------------------
**
**  Copyright (C) 2025 INDI Contributors
**
**  Permission to use, copy, modify, and/or distribute this software for
**  any purpose with or without fee is hereby granted.
**
**--------------------------------------------------------------------*/
