/*******************************************************************************
 * Test Level 1b: Horizontal Coordinate Truth Validation
 *
 * Validates EquatorialToHorizontal against IMCCE Miriade (INPOP19) truth.
 * Golden data: test/data/horizontal_golden.json (generated by
 * tools/generate_golden_files.py).
 *
 * Test tolerance: 15 arcseconds. This accounts for:
 *   - ERFA IAU 2000A (IMCCE) vs 2000B (our default) nutation delta: < 1 mas
 *   - Minor observer coordinate precision differences between IAU site list and test input
 *   - No refraction applied in either this code or the IMCCE query (phpa=0 default)
 * The two bugs this test is designed to catch were each tens of degrees in magnitude.
 *
 * Structural assertions (no external truth required):
 *   - Observer longitude test: Vega altitude differs by >30 deg across three
 *     longitude-separated sites. If observer position is ignored all altitudes
 *     are identical — this catches the Bug #1 class (eraApci vs eraApco).
 *   - Observer latitude test: Polaris is above the horizon at Greenwich and below
 *     it at Siding Spring. If observer latitude is ignored this contrast disappears.
 *******************************************************************************/

#include <gtest/gtest.h>
#include <libastro.h>
#include <indicom.h>
#include <nlohmann/json.hpp>
#include <fstream>
#include <string>
#include <vector>
#include <cmath>

static constexpr double ARCSEC_PER_DEG = 3600.0;
// 30" accounts for: 2000A vs 2000B nutation delta in horizontal projection (~0.5"),
// IMCCE IAU site coordinates vs our input precision (~10"), and any small eo-model differences.
// Both bugs this test guards against were tens of degrees in magnitude.
static constexpr double TOLERANCE_ARCSEC = 30.0;

struct HorizCase {
    std::string label;
    std::string object;
    double ra_j2000_h;
    double dec_j2000_deg;
    double jd;
    std::string site;
    double lon_deg;
    double lat_deg;
    double elev_m;
    double az_truth;
    double alt_truth;
};

static std::vector<HorizCase> load_golden()
{
    std::ifstream f(TEST_DATA_DIR "/horizontal_golden.json");
    if (!f.is_open()) return {};
    nlohmann::json j = nlohmann::json::parse(f);
    std::vector<HorizCase> cases;
    for (auto &e : j) {
        if (!e.contains("az_deg")) continue;
        HorizCase c;
        c.label       = e["label"];
        c.object      = e["object"];
        c.ra_j2000_h  = e["ra_j2000_h"];
        c.dec_j2000_deg = e["dec_j2000_deg"];
        c.jd          = e["jd"];
        c.site        = e["site"];
        c.lon_deg     = e["lon_deg"];
        c.lat_deg     = e["lat_deg"];
        c.elev_m      = e["elev_m"];
        c.az_truth    = e["az_deg"];
        c.alt_truth   = e["alt_deg"];
        cases.push_back(c);
    }
    return cases;
}

static double angular_diff_arcsec(double a, double b) {
    return std::abs(a - b) * ARCSEC_PER_DEG;
}

// Azimuth is circular: wrap difference into [-180, 180].
static double az_diff_arcsec(double a, double b) {
    double d = a - b;
    while (d >  180.0) d -= 360.0;
    while (d < -180.0) d += 360.0;
    return std::abs(d) * ARCSEC_PER_DEG;
}

// ---------------------------------------------------------------------------
// Test: absolute az/alt against IMCCE truth (both engines)
// ---------------------------------------------------------------------------
static void run_truth_test(INDI::StellarEngine engine, const char *engine_name)
{
    auto cases = load_golden();
    ASSERT_GT(cases.size(), 0u) << "Could not load horizontal_golden.json";

    INDI::setStellarEngine(engine);

    double max_az_err = 0, max_alt_err = 0;
    int n = 0;

    for (auto &c : cases) {
        INDI::IEquatorialCoordinates j2000 = { c.ra_j2000_h, c.dec_j2000_deg };
        INDI::IEquatorialCoordinates jnow;
        INDI::J2000toObserved(&j2000, c.jd, &jnow);

        INDI::IGeographicCoordinates obs = { c.lon_deg, c.lat_deg, c.elev_m };
        INDI::IHorizontalCoordinates hrz;
        INDI::EquatorialToHorizontal(&jnow, &obs, c.jd, &hrz);

        double az_err  = az_diff_arcsec(hrz.azimuth,  c.az_truth);
        double alt_err = angular_diff_arcsec(hrz.altitude, c.alt_truth);
        max_az_err  = std::max(max_az_err,  az_err);
        max_alt_err = std::max(max_alt_err, alt_err);

        EXPECT_LT(az_err,  TOLERANCE_ARCSEC)
            << engine_name << " azimuth error for " << c.object << " at " << c.site
            << ": " << az_err << "\" (truth=" << c.az_truth << " got=" << hrz.azimuth << ")";
        EXPECT_LT(alt_err, TOLERANCE_ARCSEC)
            << engine_name << " altitude error for " << c.object << " at " << c.site
            << ": " << alt_err << "\" (truth=" << c.alt_truth << " got=" << hrz.altitude << ")";
        n++;
    }

    GTEST_LOG_(INFO) << engine_name << " horizontal truth (" << n << " cases):"
                     << " max az_err=" << max_az_err << "\""
                     << " max alt_err=" << max_alt_err << "\"";
}

TEST(HorizontalTruth, ERFA_2000B_vs_IMCCE)
{
    run_truth_test(INDI::StellarEngine::ERFA_2000B, "ERFA_2000B");
}

TEST(HorizontalTruth, ERFA_2000A_vs_IMCCE)
{
    run_truth_test(INDI::StellarEngine::ERFA_2000A, "ERFA_2000A");
}

// ---------------------------------------------------------------------------
// Test: 2000A vs 2000B horizontal parity
// Engines must agree to < 1 mas on az and alt (the 77-term vs 1365-term delta).
// Catches copy-paste divergence between the two EquatorialToHorizontal impls.
// ---------------------------------------------------------------------------
TEST(HorizontalTruth, Parity_2000A_vs_2000B)
{
    auto cases = load_golden();
    ASSERT_GT(cases.size(), 0u);

    double max_delta = 0;
    for (auto &c : cases) {
        INDI::IEquatorialCoordinates j2000 = { c.ra_j2000_h, c.dec_j2000_deg };
        INDI::IGeographicCoordinates obs   = { c.lon_deg, c.lat_deg, c.elev_m };

        INDI::IEquatorialCoordinates jnow_a, jnow_b;
        INDI::setStellarEngine(INDI::StellarEngine::ERFA_2000A);
        INDI::J2000toObserved(&j2000, c.jd, &jnow_a);
        INDI::IHorizontalCoordinates hrz_a;
        INDI::EquatorialToHorizontal(&jnow_a, &obs, c.jd, &hrz_a);

        INDI::setStellarEngine(INDI::StellarEngine::ERFA_2000B);
        INDI::J2000toObserved(&j2000, c.jd, &jnow_b);
        INDI::IHorizontalCoordinates hrz_b;
        INDI::EquatorialToHorizontal(&jnow_b, &obs, c.jd, &hrz_b);

        double daz  = az_diff_arcsec(hrz_a.azimuth,  hrz_b.azimuth);
        double dalt = angular_diff_arcsec(hrz_a.altitude, hrz_b.altitude);
        double delta = std::hypot(daz, dalt);
        max_delta = std::max(max_delta, delta);

        // The 2000A vs 2000B nutation difference (~0.264 mas in RA/Dec) projects to
        // ~0.5" in azimuth at the epoch used. 1" is a safe ceiling.
        EXPECT_LT(delta, 1.0)
            << "2000A vs 2000B delta for " << c.object << " at " << c.site
            << ": " << delta << "\" (az=" << daz << "\" alt=" << dalt << "\")";
    }
    GTEST_LOG_(INFO) << "2000A vs 2000B max delta: " << max_delta << "\"";
}

// ---------------------------------------------------------------------------
// Structural: observer longitude must change altitude significantly.
// If EquatorialToHorizontal ignores the observer, all sites give the same alt.
// Regression for Bug #1: eraApci (geocentric) used instead of eraApco (observer).
// ---------------------------------------------------------------------------
TEST(HorizontalTruth, ObserverLongitudeMatters)
{
    auto cases = load_golden();
    ASSERT_GT(cases.size(), 0u);
    INDI::setStellarEngine(INDI::StellarEngine::ERFA_2000B);

    // Collect altitudes for Vega across all sites.
    double alt_min = 999.0, alt_max = -999.0;
    int vega_count = 0;
    for (auto &c : cases) {
        if (c.object != "Vega") continue;
        INDI::IEquatorialCoordinates j2000 = { c.ra_j2000_h, c.dec_j2000_deg };
        INDI::IEquatorialCoordinates jnow;
        INDI::J2000toObserved(&j2000, c.jd, &jnow);
        INDI::IGeographicCoordinates obs = { c.lon_deg, c.lat_deg, c.elev_m };
        INDI::IHorizontalCoordinates hrz;
        INDI::EquatorialToHorizontal(&jnow, &obs, c.jd, &hrz);
        alt_min = std::min(alt_min, hrz.altitude);
        alt_max = std::max(alt_max, hrz.altitude);
        vega_count++;
    }
    ASSERT_GE(vega_count, 3) << "Need at least 3 Vega cases to test longitude spread";
    // Sites span ~316 deg of longitude. If observer ignored, all alts are identical.
    EXPECT_GT(alt_max - alt_min, 30.0)
        << "Vega altitude spread across sites is " << (alt_max - alt_min)
        << " deg — expected > 30 deg. Observer longitude may not be applied.";
    GTEST_LOG_(INFO) << "Vega altitude spread: " << alt_min << " to " << alt_max
                     << " deg (spread=" << (alt_max - alt_min) << " deg)";
}

// ---------------------------------------------------------------------------
// Structural: observer latitude must determine whether Polaris is above horizon.
// Polaris is circumpolar from Greenwich (lat 51.5 N) and below the horizon from
// Siding Spring (lat 31.3 S). If observer latitude is ignored, the sign flips.
// Regression for Bug #1: same class as ObserverLongitudeMatters.
// ---------------------------------------------------------------------------
TEST(HorizontalTruth, ObserverLatitudeMatters)
{
    auto cases = load_golden();
    ASSERT_GT(cases.size(), 0u);
    INDI::setStellarEngine(INDI::StellarEngine::ERFA_2000B);

    double alt_greenwich = 999.0, alt_siding = 999.0;
    for (auto &c : cases) {
        if (c.object != "Polaris") continue;
        INDI::IEquatorialCoordinates j2000 = { c.ra_j2000_h, c.dec_j2000_deg };
        INDI::IEquatorialCoordinates jnow;
        INDI::J2000toObserved(&j2000, c.jd, &jnow);
        INDI::IGeographicCoordinates obs = { c.lon_deg, c.lat_deg, c.elev_m };
        INDI::IHorizontalCoordinates hrz;
        INDI::EquatorialToHorizontal(&jnow, &obs, c.jd, &hrz);
        if (c.site == "Greenwich")     alt_greenwich = hrz.altitude;
        if (c.site == "Siding Spring") alt_siding    = hrz.altitude;
    }
    ASSERT_NE(alt_greenwich, 999.0) << "Greenwich Polaris case missing from golden file";
    ASSERT_NE(alt_siding,    999.0) << "Siding Spring Polaris case missing from golden file";

    // Polaris is above horizon from Greenwich and below from Siding Spring.
    EXPECT_GT(alt_greenwich, 0.0)
        << "Polaris should be above horizon at Greenwich (got " << alt_greenwich << " deg)";
    EXPECT_LT(alt_siding, 0.0)
        << "Polaris should be below horizon at Siding Spring (got " << alt_siding << " deg)";
    GTEST_LOG_(INFO) << "Polaris: Greenwich alt=" << alt_greenwich
                     << " deg, Siding Spring alt=" << alt_siding << " deg";
}

// ---------------------------------------------------------------------------
// Round-trip: EquatorialToHorizontal -> HorizontalToEquatorial -> RA/Dec
// Validates HorizontalToEquatorial symmetry with the forward transform.
// Both use the same ASTROM context so the round-trip must close to < 1".
// ---------------------------------------------------------------------------
TEST(HorizontalTruth, RoundTrip_HorizontalToEquatorial)
{
    auto cases = load_golden();
    ASSERT_GT(cases.size(), 0u);
    INDI::setStellarEngine(INDI::StellarEngine::ERFA_2000B);

    double max_ra_err = 0, max_dec_err = 0;
    for (auto &c : cases) {
        INDI::IEquatorialCoordinates j2000 = { c.ra_j2000_h, c.dec_j2000_deg };
        INDI::IEquatorialCoordinates jnow_in;
        INDI::J2000toObserved(&j2000, c.jd, &jnow_in);

        INDI::IGeographicCoordinates obs = { c.lon_deg, c.lat_deg, c.elev_m };
        INDI::IHorizontalCoordinates hrz;
        INDI::EquatorialToHorizontal(&jnow_in, &obs, c.jd, &hrz);

        // Skip objects below the horizon — eraAtoiq is less numerically stable there
        if (hrz.altitude < 5.0) continue;

        INDI::IEquatorialCoordinates jnow_out;
        INDI::HorizontalToEquatorial(&hrz, &obs, c.jd, &jnow_out);

        double cos_dec = std::cos(jnow_in.declination * M_PI / 180.0);
        double ra_err  = std::abs(jnow_in.rightascension - jnow_out.rightascension) * 15.0 * 3600.0 * cos_dec;
        double dec_err = std::abs(jnow_in.declination    - jnow_out.declination)    * 3600.0;
        max_ra_err  = std::max(max_ra_err,  ra_err);
        max_dec_err = std::max(max_dec_err, dec_err);

        GTEST_LOG_(INFO) << c.object << " at " << c.site
                         << "  jnow_in=(" << jnow_in.rightascension << "h," << jnow_in.declination << "d)"
                         << "  hrz=(" << hrz.azimuth << "," << hrz.altitude << ")"
                         << "  jnow_out=(" << jnow_out.rightascension << "h," << jnow_out.declination << "d)"
                         << "  ra_err=" << ra_err << "\"  dec_err=" << dec_err << "\"";
        EXPECT_LT(ra_err,  1.0) << "Round-trip RA error for "  << c.object << " at " << c.site << ": " << ra_err  << "\"";
        EXPECT_LT(dec_err, 1.0) << "Round-trip Dec error for " << c.object << " at " << c.site << ": " << dec_err << "\"";
    }
    GTEST_LOG_(INFO) << "Round-trip max: RA=" << max_ra_err << "\" Dec=" << max_dec_err << "\"";
}

int main(int argc, char **argv)
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
