// Generates horizontal_golden.json using canonical ERFA eraAtco13 (IAU 2000A).
// This is independent from the eraApco00b (IAU 2000B) path under test.
// 2000A vs 2000B delta is < 1 mas — well within the 5" test tolerance.
//
// All inputs match the test code: dut1=0, xp=yp=0, phpa=0 (no refraction), wl=0.55.
//
// Build: cc $(pkg-config --cflags --libs erfa) -lm -o gen_horizontal_golden tools/gen_horizontal_golden.c
// Run:   ./gen_horizontal_golden > test/data/horizontal_golden.json
#include <erfa.h>
#include <erfam.h>
#include <stdio.h>
#include <math.h>

static void gen(const char *label, const char *object,
                double ra_h, double dec_deg,
                double jd,
                const char *site, double lon, double lat, double elev)
{
    double utc1 = floor(jd) + 0.5, utc2 = jd - utc1;
    double rc = ra_h * 15.0 * ERFA_DD2R;
    double dc = dec_deg * ERFA_DD2R;
    double aob, zob, hob, dob, rob, eo;
    int st = eraAtco13(rc, dc, 0,0,0,0,
                       utc1, utc2, 0.0,
                       lon * ERFA_DD2R, lat * ERFA_DD2R, elev,
                       0,0, 0,0,0, 0.55,
                       &aob, &zob, &hob, &dob, &rob, &eo);
    double az  = aob * ERFA_DR2D;
    double alt = 90.0 - zob * ERFA_DR2D;
    printf("  {\"label\":\"%s\", \"object\":\"%s\","
           " \"ra_j2000_h\":%.8f, \"dec_j2000_deg\":%.8f,"
           " \"jd\":%.5f,"
           " \"site\":\"%s\", \"lon_deg\":%.4f, \"lat_deg\":%.4f, \"elev_m\":%.1f,"
           " \"az_deg\":%.8f, \"alt_deg\":%.8f, \"erfa_status\":%d},\n",
           label, object, ra_h, dec_deg, jd,
           site, lon, lat, elev, az, alt, st);
}

int main(void)
{
    // JD 2459580.5 = 2022-Jan-01 00:00:00 UTC
    double jd = 2459580.5;

    printf("[\n");

    // Case A: Vega at three longitudes — observer longitude must affect altitude.
    // Structural assertion: max(alt)-min(alt) > 30 deg catches Bug #1 (observer ignored)
    // without needing external truth. Plus each value within 5" of this eraAtco13 reference.
    gen("A_greenwich", "Vega",  18.61564225, 38.78368178, jd,
        "Greenwich",    0.0000,  51.4779, 10.0);
    gen("A_tokyo",     "Vega",  18.61564225, 38.78368178, jd,
        "Tokyo",      139.6917,  35.6895, 10.0);
    gen("A_honolulu",  "Vega",  18.61564225, 38.78368178, jd,
        "Honolulu",  -157.8583,  21.3069, 10.0);

    // Case C: Polaris at high northern latitude — observer latitude must matter.
    // At lat=78.2, Polaris alt ~ 77.5 deg (circumpolar, alt ~ lat at upper transit).
    // If observer latitude ignored altitude is completely wrong.
    gen("C_longyearbyen", "Polaris", 2.53030388, 89.26410897, jd,
        "Longyearbyen", 15.6361, 78.2232, 10.0);

    // Case D: Equatorial geometry — Mintaka (dec ~ 0) at equatorial site.
    // Mintaka J2000: RA=5.53344h, Dec=-0.29926 deg
    gen("D_equator_mintaka", "Mintaka", 5.53344000, -0.29926000, jd,
        "Quito", -78.4678, -0.1807, 2850.0);

    // Case E: Southern hemisphere — Canopus at Siding Spring
    gen("E_siding_spring", "Canopus", 6.39919417, -52.69565556, jd,
        "Siding Spring", 149.0661, -31.2770, 1165.0);

    // Case F: Object well below horizon — Deneb at Quito (negative altitude)
    gen("F_deneb_quito", "Deneb", 20.69053168, 45.28033881, jd,
        "Quito", -78.4678, -0.1807, 2850.0);

    printf("  {\"note\":\"generated by tools/gen_horizontal_golden.c using eraAtco13 (IAU 2000A); 2000A vs 2000B delta < 1 mas\"}\n");
    printf("]\n");
    return 0;
}
